import type { Company, Enquiry, Opportunity, Person, Project, Task } from '@/types/domain'

export const demoPeople: Person[] = [
  {
    id: 'p-1',
    first_name: 'Sarah',
    last_name: 'Jenkins',
    email: 'sarah.jenkins@acmecorp.com',
    phone: '+1 (555) 234-5678',
    relationship_status: 'active_client',
    source: 'public_enquiry',
    owner_id: 'demo-user-1',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
    notes: 'Key stakeholder for the Q3 web application redesign.',
  },
  {
    id: 'p-2',
    first_name: 'David',
    last_name: 'Miller',
    email: 'david.m@apexlogistics.io',
    phone: '+1 (555) 876-5432',
    relationship_status: 'prospect',
    source: 'manual',
    owner_id: 'demo-user-1',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 18).toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
    notes: 'Evaluating delivery tracking integration.',
  },
  {
    id: 'p-3',
    first_name: 'Elena',
    last_name: 'Rostova',
    email: 'elena@novadesign.co',
    phone: '+44 20 7946 0912',
    relationship_status: 'active_client',
    source: 'referral',
    owner_id: 'demo-user-1',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 35).toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
    notes: 'Brand design system and UI library deliverables.',
  },
  {
    id: 'p-4',
    first_name: 'Marcus',
    last_name: 'Chen',
    email: 'marcus.chen@quantumsoft.com',
    phone: '+1 (555) 432-1098',
    relationship_status: 'lead',
    source: 'public_enquiry',
    owner_id: 'demo-user-1',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
    notes: 'Inquired about enterprise authentication setup.',
  },
  {
    id: 'p-5',
    first_name: 'Amara',
    last_name: 'Okonkwo',
    email: 'amara@solargreen.org',
    phone: '+234 1 234 5678',
    relationship_status: 'past_client',
    source: 'manual',
    owner_id: 'demo-user-1',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 90).toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
    notes: 'Completed renewable energy dashboard project.',
  },
]

export const demoCompanies: Company[] = [
  {
    id: 'c-1',
    name: 'Northstar Bicycle Co.',
    website: 'https://northstarbikes.com',
    email: 'hello@northstarbikes.com',
    phone: '+1 (555) 300-1234',
    industry: 'Manufacturing & Retail',
    status: 'active_client',
    owner_id: 'demo-user-1',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
    notes: 'Custom gravel and urban commuter bikes.',
  },
  {
    id: 'c-2',
    name: 'Apex Logistics IO',
    website: 'https://apexlogistics.io',
    email: 'ops@apexlogistics.io',
    phone: '+1 (555) 400-5678',
    industry: 'Logistics & Tech',
    status: 'prospect',
    owner_id: 'demo-user-1',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
    notes: 'Freight tracking APIs and automated dispatch.',
  },
  {
    id: 'c-3',
    name: 'Nova Design Studio',
    website: 'https://novadesign.co',
    email: 'contact@novadesign.co',
    phone: '+44 20 7946 0123',
    industry: 'Design & Creative',
    status: 'active_client',
    owner_id: 'demo-user-1',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
    notes: 'Digital product design and design systems.',
  },
  {
    id: 'c-4',
    name: 'Solar Green Energy',
    website: 'https://solargreen.org',
    email: 'info@solargreen.org',
    phone: '+234 1 234 5678',
    industry: 'Clean Energy',
    status: 'past_client',
    owner_id: 'demo-user-1',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 90).toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
    notes: 'Community solar initiative and analytics.',
  },
]

export const demoOpportunities: Opportunity[] = [
  {
    id: 'opp-1',
    owner_id: 'demo-user-1',
    person_id: 'p-1',
    company_id: 'c-1',
    enquiry_id: null,
    title: 'Enterprise Redesign & Design System',
    service_interest: 'Web Design',
    stage: 'proposal',
    expected_value: 48000,
    probability: 70,
    expected_close_date: '2026-09-15',
    next_action: 'Send revised contract',
    next_action_due_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2).toISOString(),
    notes: 'Approved initial wireframes.',
    stage_reason: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
  },
  {
    id: 'opp-2',
    owner_id: 'demo-user-1',
    person_id: 'p-2',
    company_id: 'c-2',
    enquiry_id: null,
    title: 'API Integration & Dispatch Automations',
    service_interest: 'Backend API',
    stage: 'discovery',
    expected_value: 22500,
    probability: 40,
    expected_close_date: '2026-09-30',
    next_action: 'Technical discovery call',
    next_action_due_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 4).toISOString(),
    notes: 'Requires webhook architecture.',
    stage_reason: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
  },
  {
    id: 'opp-3',
    owner_id: 'demo-user-1',
    person_id: 'p-3',
    company_id: 'c-3',
    enquiry_id: null,
    title: 'Q3 Retainer & Component Maintenance',
    service_interest: 'Design System',
    stage: 'won',
    expected_value: 65000,
    probability: 100,
    expected_close_date: '2026-08-01',
    next_action: 'Monthly review',
    next_action_due_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 15).toISOString(),
    notes: 'Closed successfully.',
    stage_reason: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
  },
  {
    id: 'opp-4',
    owner_id: 'demo-user-1',
    person_id: 'p-4',
    company_id: null,
    enquiry_id: null,
    title: 'Security Architecture Audit & AAL2',
    service_interest: 'Security',
    stage: 'negotiation',
    expected_value: 34000,
    probability: 85,
    expected_close_date: '2026-09-08',
    next_action: 'Scope sign-off',
    next_action_due_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    notes: 'Final contract in legal review.',
    stage_reason: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
  },
]

export const demoProjects: Project[] = [
  {
    id: 'proj-1',
    owner_id: 'demo-user-1',
    title: 'Website & Brand Refresh',
    status: 'active',
    person_id: 'p-1',
    company_id: 'c-1',
    opportunity_id: 'opp-1',
    start_date: '2026-07-01',
    target_date: '2026-09-30',
    progress: 72,
    description: 'Full redesign with Tailwind CSS and Next.js',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
  },
  {
    id: 'proj-2',
    owner_id: 'demo-user-1',
    title: 'Partner Portal Onboarding',
    status: 'active',
    person_id: 'p-2',
    company_id: 'c-2',
    opportunity_id: 'opp-2',
    start_date: '2026-07-15',
    target_date: '2026-10-15',
    progress: 45,
    description: 'Self-service registration and key management',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
  },
  {
    id: 'proj-3',
    owner_id: 'demo-user-1',
    title: 'Catalogue Automation Service',
    status: 'completed',
    person_id: 'p-3',
    company_id: 'c-3',
    opportunity_id: 'opp-3',
    start_date: '2026-06-01',
    target_date: '2026-07-31',
    progress: 100,
    description: 'Automated photo sync and inventory update pipelines',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
  },
]

export const demoTasks: Task[] = [
  {
    id: 'task-1',
    owner_id: 'demo-user-1',
    project_id: 'proj-1',
    parent_task_id: null,
    milestone_id: null,
    task_group_id: null,
    title: 'Send revised scope document to Northstar',
    description: 'Include design deliverables breakdown.',
    status: 'in_progress',
    priority: 'high',
    start_at: new Date().toISOString(),
    due_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 1).toISOString(),
    estimate_minutes: 60,
    position: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
  },
  {
    id: 'task-2',
    owner_id: 'demo-user-1',
    project_id: 'proj-2',
    parent_task_id: null,
    milestone_id: null,
    task_group_id: null,
    title: 'Review partner onboarding checklist and test keys',
    description: 'Verify OAuth redirection callbacks.',
    status: 'todo',
    priority: 'normal',
    start_at: null,
    due_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2).toISOString(),
    estimate_minutes: 120,
    position: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
  },
  {
    id: 'task-3',
    owner_id: 'demo-user-1',
    project_id: 'proj-1',
    parent_task_id: null,
    milestone_id: null,
    task_group_id: null,
    title: 'Finalize design system typography tokens in Tailwind',
    description: 'Inter and Outfit font configurations.',
    status: 'done',
    priority: 'normal',
    start_at: null,
    due_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
    estimate_minutes: 90,
    position: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
  },
  {
    id: 'task-4',
    owner_id: 'demo-user-1',
    project_id: null,
    parent_task_id: null,
    milestone_id: null,
    task_group_id: null,
    title: 'Update Supabase Edge Function environment variables',
    description: 'Ensure APP_ORIGIN and CRON_SECRET are current.',
    status: 'todo',
    priority: 'high',
    start_at: null,
    due_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 5).toISOString(),
    estimate_minutes: 45,
    position: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
  },
]

export const demoEnquiries: Enquiry[] = [
  {
    id: 'enq-1',
    owner_id: 'demo-user-1',
    person_id: 'p-1',
    company_id: 'c-1',
    category: 'hire',
    subject: 'Enterprise Redesign Scope',
    message: 'We are looking to overhaul our customer portal before Q4.',
    service_interest: 'Web Application Development',
    status: 'new',
    priority: 'high',
    next_action: 'Initial scoping call',
    next_action_due_at: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
  },
  {
    id: 'enq-2',
    owner_id: 'demo-user-1',
    person_id: 'p-4',
    company_id: null,
    category: 'request',
    subject: 'AAL2 Security Architecture Consultation',
    message: 'Seeking assistance with TOTP MFA setup and audit compliance.',
    service_interest: 'Security Architecture',
    status: 'reviewing',
    priority: 'normal',
    next_action: 'Send proposal template',
    next_action_due_at: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
  },
]

export function getDemoTableData<T>(table: string): T[] {
  switch (table) {
    case 'people':
      return demoPeople as unknown as T[]
    case 'companies':
      return demoCompanies as unknown as T[]
    case 'opportunities':
      return demoOpportunities as unknown as T[]
    case 'projects':
      return demoProjects as unknown as T[]
    case 'tasks':
      return demoTasks as unknown as T[]
    case 'enquiries':
      return demoEnquiries as unknown as T[]
    default:
      return []
  }
}
