import { Bell, Search } from 'lucide-react'
import { Link, useSearchParams } from 'react-router-dom'
import { visibleNavigation } from '@/components/layout/navigation'
import { Button } from '@/components/ui/Button'
import { Badge, Panel } from '@/components/ui/Panel'
import { useAuth } from '@/features/auth/AuthProvider'
import { useRows } from '@/hooks/useRows'
import { supabase } from '@/lib/supabase'

type Named={id:string;first_name?:string;last_name?:string|null;name?:string;title?:string;subject?:string}
type Notification={id:string;title:string;body:string|null;href:string|null;read_at:string|null;created_at:string;kind:string}
export function SearchPage(){const[params]=useSearchParams();const query=(params.get('q')??'').trim().toLowerCase();const{data:people}=useRows<Named>('people');const{data:companies}=useRows<Named>('companies');const{data:projects}=useRows<Named>('projects');const{data:tasks}=useRows<Named>('tasks');const records=[...people.map(item=>({...item,module:'People',href:'/people',label:`${item.first_name} ${item.last_name??''}`})),...companies.map(item=>({...item,module:'Companies',href:'/companies',label:item.name??''})),...projects.map(item=>({...item,module:'Projects',href:'/projects',label:item.title??''})),...tasks.map(item=>({...item,module:'Tasks',href:'/tasks',label:item.title??''}))].filter(item=>query&&item.label.toLowerCase().includes(query));return <main className="page"><header className="page-header"><div><p className="eyebrow">Private global search</p><h1 className="page-title">Search results</h1><p className="muted">Results are limited to records assigned to your MFA-protected account.</p></div></header><Panel>{records.length?records.map(item=><Link className="attention-row" to={item.href} key={`${item.module}-${item.id}`}><Search size={17}/><div className="grow"><strong>{item.label}</strong><small>{item.module}</small></div><Badge>{item.module}</Badge></Link>):<div className="empty"><Search size={38}/><h2>No matching records</h2><p>Try a person, company, project, or task name.</p></div>}</Panel></main>}
export function NotificationsPage(){const{data,refresh}=useRows<Notification>('notifications','created_at',false);return <main className="page"><header className="page-header"><div><p className="eyebrow">Attention queue</p><h1 className="page-title">Notifications</h1><p className="muted">New enquiries, replies, scheduling decisions, and failed operations.</p></div><Button variant="secondary" onClick={async()=>{await supabase.from('notifications').update({read_at:new Date().toISOString()}).is('read_at',null);await refresh()}}>Mark all read</Button></header><Panel>{data.length?data.map(item=><Link className="attention-row" to={item.href??'/'} key={item.id} onClick={async()=>{if(!item.read_at)await supabase.from('notifications').update({read_at:new Date().toISOString()}).eq('id',item.id)}}><Bell size={17}/><div className="grow"><strong>{item.title}</strong><small>{item.body} · {new Date(item.created_at).toLocaleString('en-IN')}</small></div>{!item.read_at&&<Badge tone="warning">New</Badge>}</Link>):<div className="empty"><Bell size={38}/><h2>No notifications</h2></div>}</Panel></main>}
export function MorePage(){const{access,signOut}=useAuth();const primary=new Set(['Home','People','Tasks','Calendar']);const items=access?visibleNavigation(access).flatMap(group=>group.items).filter(item=>!primary.has(item.label)):[];return <main className="page"><header className="page-header"><div><p className="eyebrow">Account and navigation</p><h1 className="page-title">More</h1></div><Button variant="ghost" onClick={()=>void signOut()}>Sign out</Button></header><div className="grid two"><Link className="panel panel-body row" to="/profile"><strong>My Profile</strong></Link>{items.map(({label,href,icon:Icon})=><Link className="panel panel-body row" to={href} key={href}><Icon size={20}/><strong>{label}</strong></Link>)}</div></main>}
export function NotFoundPage(){return <main className="center-screen"><div className="empty"><h1>Page not found</h1><Link className="button primary" to="/">Return home</Link></div></main>}
