import { useMemo, useState } from 'react'
import { Inbox, Send } from 'lucide-react'
import { PageHeader } from '@/components/shared/PageHeader'
import { Button } from '@/components/ui/Button'
import { TextareaField } from '@/components/ui/Field'
import { Badge, Panel } from '@/components/ui/Panel'
import { useAuth } from '@/features/auth/AuthProvider'
import { useRows } from '@/hooks/useRows'
import { supabase } from '@/lib/supabase'

type Conversation={id:string;person_id:string;subject:string;status:string;reply_needed:boolean;last_message_at:string}
type Message={id:string;conversation_id:string;direction:string;sender_email:string;body_text:string;status:string;created_at:string}
type Person={id:string;first_name:string;last_name:string|null;email:string|null}
export function InboxPage(){const{session}=useAuth();const{data:conversations,refresh}=useRows<Conversation>('conversations','last_message_at');const{data:messages,refresh:refreshMessages}=useRows<Message>('messages','created_at',false);const{data:people}=useRows<Person>('people');const[selected,setSelected]=useState<string|null>(null);const[body,setBody]=useState('');const[sending,setSending]=useState(false);const active=conversations.find(c=>c.id===(selected??conversations[0]?.id));const thread=useMemo(()=>messages.filter(m=>m.conversation_id===active?.id).sort((a,b)=>a.created_at.localeCompare(b.created_at)),[active,messages]);const person=(id:string)=>{const p=people.find(value=>value.id===id);return p?`${p.first_name} ${p.last_name??''}`.trim():'Client'};const send=async()=>{if(!active||!body.trim())return;setSending(true);const{error}=await supabase.functions.invoke('send-email',{body:{conversationId:active.id,body:body.trim()},headers:{Authorization:`Bearer ${session!.access_token}`}});setSending(false);if(error)return alert(error.message);setBody('');await Promise.all([refresh(),refreshMessages()])};return <main className="page"><PageHeader eyebrow="Communication" title="Inbox" description="Website enquiries and Resend email replies stay together as one client thread."/><div className="inbox-layout"><Panel className="inbox-list">{conversations.length?conversations.map(item=><button className={`conversation-item ${active?.id===item.id?'active':''}`} key={item.id} onClick={()=>setSelected(item.id)}><span className="row"><strong className="grow">{person(item.person_id)}</strong>{item.reply_needed&&<Badge tone="warning">Reply</Badge>}</span><span>{item.subject}</span><small>{new Date(item.last_message_at).toLocaleString('en-IN')}</small></button>):<div className="empty"><Inbox size={36}/><p>No conversations yet.</p></div>}</Panel><Panel className="thread-panel" title={active?.subject??'Select a conversation'}>{active?<><div className="message-thread">{thread.map(message=><article className={`message-bubble ${message.direction}`} key={message.id}><small>{message.direction==='outbound'?'You':message.sender_email}</small><p>{message.body_text}</p><span>{new Date(message.created_at).toLocaleString('en-IN')} · {message.status}</span></article>)}</div><div className="divider"/><TextareaField label="Reply by email" value={body} onChange={e=>setBody(e.target.value)} placeholder="Write your reply…"/><Button disabled={sending||!body.trim()} onClick={()=>void send()}><Send size={16}/>{sending?'Queueing…':'Queue reply'}</Button></>:<div className="empty"><p>Choose a client thread.</p></div>}</Panel></div></main>}
