import { useCallback, useEffect, useState } from 'react'
import { ArchiveRestore, Trash2 } from 'lucide-react'
import { PageHeader } from '@/components/shared/PageHeader'
import { Button } from '@/components/ui/Button'
import { Badge, Panel } from '@/components/ui/Panel'
import { supabase } from '@/lib/supabase'

type Trashed={id:string;label:string;table:string;deleted_at:string;purge_after:string}
const tables=[['people','first_name'],['companies','name'],['enquiries','subject'],['opportunities','title'],['projects','title'],['tasks','title'],['conversations','subject'],['files','original_name']] as const
export function TrashPage(){const[data,setData]=useState<Trashed[]>([]);const[loading,setLoading]=useState(true);const load=useCallback(async()=>{setLoading(true);const groups=await Promise.all(tables.map(async([table,label])=>{const{data:rows}=await supabase.from(table).select(`id,${label},deleted_at,purge_after`).not('deleted_at','is',null);return(rows??[]).map(row=>({id:String(row.id),label:String(Reflect.get(row,label)??'Untitled'),table,deleted_at:String(row.deleted_at),purge_after:String(row.purge_after)}))}));setData(groups.flat().sort((a,b)=>b.deleted_at.localeCompare(a.deleted_at)));setLoading(false)},[]);useEffect(()=>{void load()},[load]);const restore=async(item:Trashed)=>{const{error}=await supabase.from(item.table).update({deleted_at:null,purge_after:null}).eq('id',item.id);if(error)alert(error.message);else await load()};return <main className="page"><PageHeader eyebrow="30-day recovery" title="Trash" description="Soft-deleted records are recoverable here and are automatically purged after 30 days."/><Panel>{loading?<div className="empty"><div className="spinner"/></div>:data.length?<div className="table-wrap"><table className="table"><thead><tr><th>Record</th><th>Module</th><th>Deleted</th><th>Purges</th><th></th></tr></thead><tbody>{data.map(item=><tr key={`${item.table}-${item.id}`}><td><strong>{item.label}</strong></td><td><Badge>{item.table}</Badge></td><td>{new Date(item.deleted_at).toLocaleDateString('en-IN')}</td><td>{new Date(item.purge_after).toLocaleDateString('en-IN')}</td><td><Button variant="secondary" onClick={()=>void restore(item)}><ArchiveRestore size={16}/>Restore</Button></td></tr>)}</tbody></table></div>:<div className="empty"><Trash2 size={38}/><h2>Trash is empty</h2><p>Deleted records will remain here for 30 days.</p></div>}</Panel></main>}
